//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/********************************************************************
* Copyright (c) 2008 - 2024. Authors: seanchann <seandev@foxmail.com>
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*         http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	coreres "github.com/seanchann/apimaster/pkg/apis/coreres"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*LocalObjectReference)(nil), (*coreres.LocalObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LocalObjectReference_To_coreres_LocalObjectReference(a.(*LocalObjectReference), b.(*coreres.LocalObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.LocalObjectReference)(nil), (*LocalObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_LocalObjectReference_To_v1_LocalObjectReference(a.(*coreres.LocalObjectReference), b.(*LocalObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Namespace)(nil), (*coreres.Namespace)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Namespace_To_coreres_Namespace(a.(*Namespace), b.(*coreres.Namespace), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.Namespace)(nil), (*Namespace)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_Namespace_To_v1_Namespace(a.(*coreres.Namespace), b.(*Namespace), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceCondition)(nil), (*coreres.NamespaceCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NamespaceCondition_To_coreres_NamespaceCondition(a.(*NamespaceCondition), b.(*coreres.NamespaceCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.NamespaceCondition)(nil), (*NamespaceCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_NamespaceCondition_To_v1_NamespaceCondition(a.(*coreres.NamespaceCondition), b.(*NamespaceCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceList)(nil), (*coreres.NamespaceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NamespaceList_To_coreres_NamespaceList(a.(*NamespaceList), b.(*coreres.NamespaceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.NamespaceList)(nil), (*NamespaceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_NamespaceList_To_v1_NamespaceList(a.(*coreres.NamespaceList), b.(*NamespaceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceSpec)(nil), (*coreres.NamespaceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NamespaceSpec_To_coreres_NamespaceSpec(a.(*NamespaceSpec), b.(*coreres.NamespaceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.NamespaceSpec)(nil), (*NamespaceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_NamespaceSpec_To_v1_NamespaceSpec(a.(*coreres.NamespaceSpec), b.(*NamespaceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceStatus)(nil), (*coreres.NamespaceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NamespaceStatus_To_coreres_NamespaceStatus(a.(*NamespaceStatus), b.(*coreres.NamespaceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.NamespaceStatus)(nil), (*NamespaceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_NamespaceStatus_To_v1_NamespaceStatus(a.(*coreres.NamespaceStatus), b.(*NamespaceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectReference)(nil), (*coreres.ObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectReference_To_coreres_ObjectReference(a.(*ObjectReference), b.(*coreres.ObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.ObjectReference)(nil), (*ObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_ObjectReference_To_v1_ObjectReference(a.(*coreres.ObjectReference), b.(*ObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TypedLocalObjectReference)(nil), (*coreres.TypedLocalObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TypedLocalObjectReference_To_coreres_TypedLocalObjectReference(a.(*TypedLocalObjectReference), b.(*coreres.TypedLocalObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.TypedLocalObjectReference)(nil), (*TypedLocalObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_TypedLocalObjectReference_To_v1_TypedLocalObjectReference(a.(*coreres.TypedLocalObjectReference), b.(*TypedLocalObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TypedObjectReference)(nil), (*coreres.TypedObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TypedObjectReference_To_coreres_TypedObjectReference(a.(*TypedObjectReference), b.(*coreres.TypedObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*coreres.TypedObjectReference)(nil), (*TypedObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_coreres_TypedObjectReference_To_v1_TypedObjectReference(a.(*coreres.TypedObjectReference), b.(*TypedObjectReference), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_LocalObjectReference_To_coreres_LocalObjectReference(in *LocalObjectReference, out *coreres.LocalObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1_LocalObjectReference_To_coreres_LocalObjectReference is an autogenerated conversion function.
func Convert_v1_LocalObjectReference_To_coreres_LocalObjectReference(in *LocalObjectReference, out *coreres.LocalObjectReference, s conversion.Scope) error {
	return autoConvert_v1_LocalObjectReference_To_coreres_LocalObjectReference(in, out, s)
}

func autoConvert_coreres_LocalObjectReference_To_v1_LocalObjectReference(in *coreres.LocalObjectReference, out *LocalObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_coreres_LocalObjectReference_To_v1_LocalObjectReference is an autogenerated conversion function.
func Convert_coreres_LocalObjectReference_To_v1_LocalObjectReference(in *coreres.LocalObjectReference, out *LocalObjectReference, s conversion.Scope) error {
	return autoConvert_coreres_LocalObjectReference_To_v1_LocalObjectReference(in, out, s)
}

func autoConvert_v1_Namespace_To_coreres_Namespace(in *Namespace, out *coreres.Namespace, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_NamespaceSpec_To_coreres_NamespaceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_NamespaceStatus_To_coreres_NamespaceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Namespace_To_coreres_Namespace is an autogenerated conversion function.
func Convert_v1_Namespace_To_coreres_Namespace(in *Namespace, out *coreres.Namespace, s conversion.Scope) error {
	return autoConvert_v1_Namespace_To_coreres_Namespace(in, out, s)
}

func autoConvert_coreres_Namespace_To_v1_Namespace(in *coreres.Namespace, out *Namespace, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_coreres_NamespaceSpec_To_v1_NamespaceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_coreres_NamespaceStatus_To_v1_NamespaceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_coreres_Namespace_To_v1_Namespace is an autogenerated conversion function.
func Convert_coreres_Namespace_To_v1_Namespace(in *coreres.Namespace, out *Namespace, s conversion.Scope) error {
	return autoConvert_coreres_Namespace_To_v1_Namespace(in, out, s)
}

func autoConvert_v1_NamespaceCondition_To_coreres_NamespaceCondition(in *NamespaceCondition, out *coreres.NamespaceCondition, s conversion.Scope) error {
	out.Type = coreres.NamespaceConditionType(in.Type)
	out.Status = coreres.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1_NamespaceCondition_To_coreres_NamespaceCondition is an autogenerated conversion function.
func Convert_v1_NamespaceCondition_To_coreres_NamespaceCondition(in *NamespaceCondition, out *coreres.NamespaceCondition, s conversion.Scope) error {
	return autoConvert_v1_NamespaceCondition_To_coreres_NamespaceCondition(in, out, s)
}

func autoConvert_coreres_NamespaceCondition_To_v1_NamespaceCondition(in *coreres.NamespaceCondition, out *NamespaceCondition, s conversion.Scope) error {
	out.Type = NamespaceConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_coreres_NamespaceCondition_To_v1_NamespaceCondition is an autogenerated conversion function.
func Convert_coreres_NamespaceCondition_To_v1_NamespaceCondition(in *coreres.NamespaceCondition, out *NamespaceCondition, s conversion.Scope) error {
	return autoConvert_coreres_NamespaceCondition_To_v1_NamespaceCondition(in, out, s)
}

func autoConvert_v1_NamespaceList_To_coreres_NamespaceList(in *NamespaceList, out *coreres.NamespaceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]coreres.Namespace)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_NamespaceList_To_coreres_NamespaceList is an autogenerated conversion function.
func Convert_v1_NamespaceList_To_coreres_NamespaceList(in *NamespaceList, out *coreres.NamespaceList, s conversion.Scope) error {
	return autoConvert_v1_NamespaceList_To_coreres_NamespaceList(in, out, s)
}

func autoConvert_coreres_NamespaceList_To_v1_NamespaceList(in *coreres.NamespaceList, out *NamespaceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Namespace)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_coreres_NamespaceList_To_v1_NamespaceList is an autogenerated conversion function.
func Convert_coreres_NamespaceList_To_v1_NamespaceList(in *coreres.NamespaceList, out *NamespaceList, s conversion.Scope) error {
	return autoConvert_coreres_NamespaceList_To_v1_NamespaceList(in, out, s)
}

func autoConvert_v1_NamespaceSpec_To_coreres_NamespaceSpec(in *NamespaceSpec, out *coreres.NamespaceSpec, s conversion.Scope) error {
	out.Finalizers = *(*[]coreres.FinalizerName)(unsafe.Pointer(&in.Finalizers))
	return nil
}

// Convert_v1_NamespaceSpec_To_coreres_NamespaceSpec is an autogenerated conversion function.
func Convert_v1_NamespaceSpec_To_coreres_NamespaceSpec(in *NamespaceSpec, out *coreres.NamespaceSpec, s conversion.Scope) error {
	return autoConvert_v1_NamespaceSpec_To_coreres_NamespaceSpec(in, out, s)
}

func autoConvert_coreres_NamespaceSpec_To_v1_NamespaceSpec(in *coreres.NamespaceSpec, out *NamespaceSpec, s conversion.Scope) error {
	out.Finalizers = *(*[]FinalizerName)(unsafe.Pointer(&in.Finalizers))
	return nil
}

// Convert_coreres_NamespaceSpec_To_v1_NamespaceSpec is an autogenerated conversion function.
func Convert_coreres_NamespaceSpec_To_v1_NamespaceSpec(in *coreres.NamespaceSpec, out *NamespaceSpec, s conversion.Scope) error {
	return autoConvert_coreres_NamespaceSpec_To_v1_NamespaceSpec(in, out, s)
}

func autoConvert_v1_NamespaceStatus_To_coreres_NamespaceStatus(in *NamespaceStatus, out *coreres.NamespaceStatus, s conversion.Scope) error {
	out.Phase = coreres.NamespacePhase(in.Phase)
	out.Conditions = *(*[]coreres.NamespaceCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1_NamespaceStatus_To_coreres_NamespaceStatus is an autogenerated conversion function.
func Convert_v1_NamespaceStatus_To_coreres_NamespaceStatus(in *NamespaceStatus, out *coreres.NamespaceStatus, s conversion.Scope) error {
	return autoConvert_v1_NamespaceStatus_To_coreres_NamespaceStatus(in, out, s)
}

func autoConvert_coreres_NamespaceStatus_To_v1_NamespaceStatus(in *coreres.NamespaceStatus, out *NamespaceStatus, s conversion.Scope) error {
	out.Phase = NamespacePhase(in.Phase)
	out.Conditions = *(*[]NamespaceCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_coreres_NamespaceStatus_To_v1_NamespaceStatus is an autogenerated conversion function.
func Convert_coreres_NamespaceStatus_To_v1_NamespaceStatus(in *coreres.NamespaceStatus, out *NamespaceStatus, s conversion.Scope) error {
	return autoConvert_coreres_NamespaceStatus_To_v1_NamespaceStatus(in, out, s)
}

func autoConvert_v1_ObjectReference_To_coreres_ObjectReference(in *ObjectReference, out *coreres.ObjectReference, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.UID = types.UID(in.UID)
	out.APIVersion = in.APIVersion
	out.ResourceVersion = in.ResourceVersion
	out.FieldPath = in.FieldPath
	return nil
}

// Convert_v1_ObjectReference_To_coreres_ObjectReference is an autogenerated conversion function.
func Convert_v1_ObjectReference_To_coreres_ObjectReference(in *ObjectReference, out *coreres.ObjectReference, s conversion.Scope) error {
	return autoConvert_v1_ObjectReference_To_coreres_ObjectReference(in, out, s)
}

func autoConvert_coreres_ObjectReference_To_v1_ObjectReference(in *coreres.ObjectReference, out *ObjectReference, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.UID = types.UID(in.UID)
	out.APIVersion = in.APIVersion
	out.ResourceVersion = in.ResourceVersion
	out.FieldPath = in.FieldPath
	return nil
}

// Convert_coreres_ObjectReference_To_v1_ObjectReference is an autogenerated conversion function.
func Convert_coreres_ObjectReference_To_v1_ObjectReference(in *coreres.ObjectReference, out *ObjectReference, s conversion.Scope) error {
	return autoConvert_coreres_ObjectReference_To_v1_ObjectReference(in, out, s)
}

func autoConvert_v1_TypedLocalObjectReference_To_coreres_TypedLocalObjectReference(in *TypedLocalObjectReference, out *coreres.TypedLocalObjectReference, s conversion.Scope) error {
	out.APIVersion = (*string)(unsafe.Pointer(in.APIVersion))
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_v1_TypedLocalObjectReference_To_coreres_TypedLocalObjectReference is an autogenerated conversion function.
func Convert_v1_TypedLocalObjectReference_To_coreres_TypedLocalObjectReference(in *TypedLocalObjectReference, out *coreres.TypedLocalObjectReference, s conversion.Scope) error {
	return autoConvert_v1_TypedLocalObjectReference_To_coreres_TypedLocalObjectReference(in, out, s)
}

func autoConvert_coreres_TypedLocalObjectReference_To_v1_TypedLocalObjectReference(in *coreres.TypedLocalObjectReference, out *TypedLocalObjectReference, s conversion.Scope) error {
	out.APIVersion = (*string)(unsafe.Pointer(in.APIVersion))
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_coreres_TypedLocalObjectReference_To_v1_TypedLocalObjectReference is an autogenerated conversion function.
func Convert_coreres_TypedLocalObjectReference_To_v1_TypedLocalObjectReference(in *coreres.TypedLocalObjectReference, out *TypedLocalObjectReference, s conversion.Scope) error {
	return autoConvert_coreres_TypedLocalObjectReference_To_v1_TypedLocalObjectReference(in, out, s)
}

func autoConvert_v1_TypedObjectReference_To_coreres_TypedObjectReference(in *TypedObjectReference, out *coreres.TypedObjectReference, s conversion.Scope) error {
	out.APIVersion = (*string)(unsafe.Pointer(in.APIVersion))
	out.Kind = in.Kind
	out.Name = in.Name
	out.Namespace = (*string)(unsafe.Pointer(in.Namespace))
	return nil
}

// Convert_v1_TypedObjectReference_To_coreres_TypedObjectReference is an autogenerated conversion function.
func Convert_v1_TypedObjectReference_To_coreres_TypedObjectReference(in *TypedObjectReference, out *coreres.TypedObjectReference, s conversion.Scope) error {
	return autoConvert_v1_TypedObjectReference_To_coreres_TypedObjectReference(in, out, s)
}

func autoConvert_coreres_TypedObjectReference_To_v1_TypedObjectReference(in *coreres.TypedObjectReference, out *TypedObjectReference, s conversion.Scope) error {
	out.APIVersion = (*string)(unsafe.Pointer(in.APIVersion))
	out.Kind = in.Kind
	out.Name = in.Name
	out.Namespace = (*string)(unsafe.Pointer(in.Namespace))
	return nil
}

// Convert_coreres_TypedObjectReference_To_v1_TypedObjectReference is an autogenerated conversion function.
func Convert_coreres_TypedObjectReference_To_v1_TypedObjectReference(in *coreres.TypedObjectReference, out *TypedObjectReference, s conversion.Scope) error {
	return autoConvert_coreres_TypedObjectReference_To_v1_TypedObjectReference(in, out, s)
}
